services:
  db:
    image: postgres:17-alpine
    container_name: arcturus-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha_segura
      POSTGRES_DB: arcturus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: